name: Create envfile

on: pull_request

jobs:

  create-envfile:
 
    runs-on: ubuntu-latest
 
    steps:
    - name: Create .env file
      uses: SpicyPizza/create-envfile@v2.0.2
            
      with:
        envkey_DEBUG: false
        envkey_SOME_API_KEY: "123456abcdef"
        some_other_variable: foobar
        directory: <directory_name>
        file_name: .env
        fail_on_empty: false
        sort_keys: false
