name: Create envfile

on: 
  push
jobs:

  create-envfile:
 
    runs-on: ubuntu-latest
 
    steps:
    - name: Create .env file
      uses: Test/create-envfile@v2.0.2
            
      with:
        envkey_DEBUG: false
        envkey_SOME_API_KEY: "123456abcdef"
        some_other_variable: foobar
        file_name: .env
        fail_on_empty: false
        sort_keys: false
